config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    get '/products/import', to: "products#import", as: :import_products
    post '/products/import', to: "products#create_import", as: :create_imported_product
  end
end

app/models/core/spree/product_decorator.rb
require 'csv'

class ProductImportError < StandardError
end

Spree::Product.class_eval do
  # Import a collection of products into Spree using a csv
  def self.import(file)
    errors = []
    success_count = 0
    rows = Spree::ProductImportConfiguration[:csv_format]

    CSV.foreach(file.path) do |row|

      data = { taxonomies: [], properties: [] }

      # build the data object from the csv
      rows.each_with_index do |key, index|
        # check for taxonomies
        if(key.key?(:type) && key[:type] == Spree::Taxonomy)
          data[:taxonomies].push({ taxonomy: key[:name], taxons: row[index] })
        elsif(key.key?(:type) && key[:type] == Spree::Property)
          data[:properties].push({ name: key[:name], value: row[index] })
        else
          data[key[:name]] = row[index]
        end
      end

      # pull out the sku
      sku = data[:sku]
      data.delete(:sku)

      sku_errors = []
      sku_errors[0] = sku
      sku_errors[1] = []

      begin
        import_one(sku, data)
        success_count += 1
      rescue ProductImportError, ActiveRecord::RecordInvalid => e
        sku_errors[1] << e.message.to_s
      end

      errors << sku_errors if sku_errors[1].length > 0
    end

    result = Hash.new
    result['success'] = success_count

    if errors.length > 0
      result['failure'] = errors
    end

    return result
  end

  # Import a single product into Spree by SKU
  def self.import_one(sku, data)

    variant = Spree::Variant.find_by sku: sku
    if variant
      product = variant.product
    end
    # this can't just be an else because sometimes there is a variant but not a product for it to be attached to
    # (likely due to an earlier error with creating the same product)
    if !product
      product = new()
    end

    product.sku = sku
    product.shipping_category_id = 1
    if !product.id
      product.available_on = Date.today
    end

    product.process_data(data)

    product.import_taxonomies(data)
    result = product.save!
    product.import_properties(data)
    Rails.logger.info "************* Finished Import on product: #{product.sku} *************"
    return result
  end

  # import all provided fields
  def process_data(data)
    # data = data.stringify_keys!

    # process all non taxonomy or property cells
    data.each do |key, value|
      next if key === :taxonomies || key === :properties
      import_method = ('import_' + key.to_s).to_sym

      if(self.respond_to? import_method)
        self.send(import_method, key, value)
      else
        # Assume a straight assignment operation
        self.send(key.to_s + "=", value)
      end

    end
  end

  # Add product to taxons as a part of the import
  def import_into_taxons(taxonomy_key, taxon_codes)

    taxonomy_name = taxonomy_key.to_s.humanize

    if taxon_codes && taxon_codes.length > 0
      root_taxonomy = Spree::Taxonomy.find_or_create_by(name: taxonomy_name)
      root_taxon = root_taxonomy.root
      taxon_code_list = taxon_codes.split ','

      taxon_code_list.each do |taxon_code|
        taxon_code = taxon_code.strip

        taxon = Spree::Taxon.find_by(meta_keywords: taxon_code, taxonomy: root_taxonomy)
        taxon ||= Spree::Taxon.find_by(name: taxon_code.to_s.humanize, taxonomy: root_taxonomy)
        taxon ||= Spree::Taxon.find_or_create_by(name: taxon_code.to_s.humanize, meta_keywords: taxon_code, taxonomy: root_taxonomy, parent: root_taxon)

        if taxon && taxon.taxonomy.name == root_taxon.name
          while taxon && (taxon.id != root_taxon.id)
            taxons << taxon unless taxons.include? taxon
            taxon = taxon.parent
          end
        end
      end

    end
  end

  # process taxonomies
  def import_taxonomies(data)
    if data[:taxonomies].length > 0
      data[:taxonomies].each do |value|
        import_into_taxons(value[:taxonomy], value[:taxons])
      end

      # remove key
      data.delete(:taxonomies)
    end
  end

  # process properties
  def import_properties(data)
    if data[:properties].length > 0
      data[:properties].each do |value|

        if !(value[:value].nil? || value[:value].empty?)
          set_property(value[:name].to_s.humanize, value[:value])
        end
      end

      # remove key
      data.delete(:properties)
    end
  end

  # import image by url
  def import_image_url(key, value)
    image_uri = value
    if self.images.length == 0
      begin
        self.images << Spree::Image.create!({
              :attachment => open(URI.parse(image_uri).to_s),
              :viewable => self
            })
      rescue OpenURI::HTTPError => e
        Rails.logger.info "Image not found for product " + sku
      end
    end
  end
end

app/models/spree/spree_product_import_configuration.rb
module Spree
  class SpreeProductImportConfiguration < Preferences::Configuration
    preference :csv_format, :array, default: [
      { name: :sku, type: String },
      { name: :image_name, type: String },
      { name: :meta_title, type: String },
      { name: :meta_keywords, type: String },
      { name: :meta_description, type: String }
    ]
  end
end

app/controllers/backend/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do

  # GET /admin/products/import
  def import
    @csv_format = Spree::ProductImportConfiguration[:csv_format]
  end

  # POST /admin/products/import
  def create_import
    @csv_format = Spree::ProductImportConfiguration[:csv_format]
    import_result = Spree::Product.import(params[:csv])
    flash[:success] = import_result['success'].to_s + ' Products successfully imported'
    @errors = import_result['failure']
    render action: 'import'
  end
end

app/views/spree/admin/products/import.html.erb
<% content_for :page_title do %>
  Import Products
<% end %>

<% if @errors %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-danger alert-auto-disappear">
        <%= @errors.length %> products were unable to save due to the following errors
        <% for error in @errors %>
          <p>
            <strong><%= error[0] %></strong><br>
          </p>
          <ul class="ul-with-markup">
            <% for message in error[1] %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<h5>CSV Format</h5>
<table class="table">
  <thead>
    <tr>
      <% @csv_format.each do |row| %>
      <th><%= row[:name] %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @csv_format.each do |row| %>
      <td><%= row[:type] %></td>
      <% end %>
    </tr>
  </tbody>
</table>

<hr>

<%= form_tag admin_create_imported_product_path, :multipart => true do %>
  <fieldset>
    <div data-hook="admin_product_form_fields">

      <div class="row">
        <div class="col-md-6" data-hook="admin_product_form_name">
          <div class="form-group field">
            <%= label_tag 'Upload CSV' %>
            <%= file_field_tag :csv, class: 'form-control title' %>
          </div>
        </div>
      </div>

      <div class="form-actions">
        <%= submit_tag 'Import', :class => 'btn btn-primary btn-success' %>
      </div>

    </div>
  </fieldset>
<% end %>

app/views/spree/admin/shared/sub_menu/_product_with_import.html.erb
<%= tab :import_products %>